name: Docker Image Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Tesseract API
        run: cd ~/tesseract-api && docker build . --file Dockerfile --tag tesseract:$(date +%s)
      - name: Build Front-End Web
        run: cd ~/frontend && docker build . --file Dockerfile --tag frontend:$(date +%s)
